[project]
name = "personal-app-backend"
version = "1.0.3"
description = "This is the backend of the personal app."
requires-python = ">=3.14,<3.15"
dependencies = [

  # software engineering & api
  "fastapi[standard]",

  "pydantic==2.13.4",
  "pydantic-settings==2.14.2",
  "loguru==0.7.3",
  "requests==2.34.2",
  "psutil>=6.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
